### ISSUE TITLE
Invalid array loop benchmarks

### ISSUE THREAD

**Issue by blacha** [majimboo/node-benchmarks#3]
The following array_loop benchmarks are invalid and should be removed

`order`, `order validation` and `pop`

All three of these remove elements from the array so subsequent tests will not iterate over the entire array.

Without regenerating the array before each test I am not sure how you can test these.

Also both `order` and `pop` do not iterate over the entire array, as when the value is `0` they will exit before processing it.

**Comment by majimboo** [comment]
Copying the array with slice and then using that copy to iterate over should solve the first problem. 

You are right. But i'll keep `order validation` and make `pop` to `pop validation`. Thank you for pointing that out.
